---
- name: IIS additional package installation
  win_chocolatey:
    name: '{{ item }}'
    state: 'latest'
  with_items:
    - '{{ addition_script }}'
  ignore_errors: yes

- name: IIS additional scripts transfer
  win_template:
    src: '{{ item }}'
    dest: 'c:\Windows\{{ item }}'
  with_items:
    - '{{ addition_script }}'
