---
- name: Remove IIS default web site
  win_iis_website:
    name: 'Default Web Site'
    state: absent

- name: Remove IIS default application pool
  win_iis_webapppool:
    name: 'DefaultAppPool'
    state: absent

- name: Configure IIS app pool
  win_iis_webapppool:
    name: '{{ iis_app_pool_name }}'
    state: started
    attributes:
      '{{ iis_app_pool_attributes }}'
  when: iis_app_pool_name|default("",true)

- name: Create IIS directory structure
  win_file:
    path: '{{ item }}'
    state: directory
  with_items:
     - '{{ iis_acl_path }}'

- name: Allow IIS group access to site path
  win_acl:
    path: '{{ item }}'
    user: '{{ iis_acl_user|default(omit,true) }}'
    rights: '{{ iis_acl_rights|default(omit,true) }}'
    type: '{{ iis_acl_type|default(omit,true) }}'
    state: '{{ iis_acl_state|default(omit,true) }}'
    inherit: '{{ iis_acl_inherit|default(omit,true) }}'
    propagation: '{{ iis_acl_propagation|default(omit,true) }}'
  with_items:
     - '{{ iis_acl_path }}'

- name: IIS system configuration 
  win_shell: 'C:\Windows\System32\inetsrv\appcmd.exe set config {{ item }} /commit:apphost' 
  with_items:
    - '{{ iis_sys_conf }}'
  ignore_errors: true
  no_log: true

- name: Upload custom web.config from template
  win_template:
    src: '{{ iis_site_web_config }}'
    dest: '{{ iis_site_path|mandatory }}/web.config'
    force: '{{ iis_site_web_config_force|default(true) }}'
  when: iis_site_web_config|default("",true)
  notify: Restart IIS service

- name: Configure IIS site
  win_iis_website:
    name: '{{ iis_site_name }}'
    physical_path: '{{ iis_site_path|default(omit,true) }}'
    parameters: '{{ iis_site_parameters|default(omit,true) }}'
    site_id: '{{ iis_site_id|default(omit,true) }}'
    ip: '{{ iis_site_ip|default(omit,true) }}'
    port: '{{ iis_site_port|default(omit,true) }}'
    ssl: '{{ iis_site_ssl|default(false) }}'
    hostname: '{{ iis_site_name|default(omit,true) }}'
    application_pool: '{{ iis_app_pool_name|default(omit,true) }}'
    state: '{{ iis_site_state|default("started",true) }}'
  when: iis_site_name|default("",true)
  register: iis_site
  notify: Restart IIS service

- name: Configure site bindings
  win_iis_webbinding:
    name: '{{iis_site_name}}'
    host_header: '{{ iis_site_name }}'
    ip: '{{item.ip|default(iis_binding_ip,true)|default(omit,true)}}'
    port: '{{item.port|default(iis_binding_port,true)|default(omit,true)}}'
    protocol: '{{item.protocol|default(iis_binding_protocol,true)|default(omit,true)}}'
    certificate_store_name: '{{item.certificate_store_name|default(iis_binding_certificate_store_name,true)|default(omit,true)}}'
    certificate_hash: '{{item.certificate_hash|default(iis_binding_certificate_hash,true)|default(omit,true)}}'
    state: '{{item.state|default(iis_binding_state,true)|default(omit,true)}}'
  with_items: '{{iis_bindings|default([])}}'
  when: iis_site_name|default("",true)
  notify: Restart IIS service

- name: Create a scheduled task to delete log that are older than a certain age
  win_scheduled_task:
    name: 'IIS access log rotate'
    description: 'Delete old log files by script'
    executable: cscript.exe
    arguments: c:\Windows\retentionscript.vbs
    time: '{{ 5|random(start=1) }}am'
    state: present
    enabled: yes
    user: SYSTEM
    triggers:
    - type: daily
      start_boundary: '2017-10-09T0{{ 5|random(start=1) }}:00:00'