---
- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: '{{ item }}'
    state: present
    restart: True
    include_sub_features: False
    include_management_tools: True
  with_items:
    - '{{ iis_feature }}'
